### ISSUE TITLE
the "totem" effect does not work in game after the new banks are applied

### ISSUE THREAD

**Issue by Jevillovaniaa** [Raltyro/PT-FSPRO-Recreation#8]
idk why this happens

**Comment by Raltyro** [comment]
Will check it when i get home, thanjs

**Comment by Jevillovaniaa** [comment]
just found that it it still works on the mod music file, so it only breaks the base game music and not the added music

**Comment by Jevillovaniaa** [comment]
ok so you need to drag in the music and sfx files (not the modded ones) for totem to work. you van make a file new file in the sounds, desktop folder to not have to replace the music files. ya so it kind of be fixxed like that
