### ISSUE TITLE
Noise uses Peppino voice lines

### ISSUE THREAD

**Issue by GenericPsycho** [Raltyro/PT-FSPRO-Recreation#9]
Being while receaving damage, collecting toppins, being idle and using transformations, The Noise will use the Peppino sound effects for some alien reason. I tried to change and add parameters but no luck.

**Comment by Raltyro** [comment]
This is because it havent been updated yet since halloween update, please stay tuned for the next commits/updates for the fspro, probably, i feel unmotivated todo anything at the moment

**Comment by Raltyro** [comment]
should be all okay now, i didnt even noticed awfulnasty kept updating this my bad
